version: 2.1
orbs:
 node: circleci/node@5.1.0
 aws-cli: circleci/aws-cli@1.3.1
jobs:
 build-test-deploy:
  docker:
     - image: 'cimg/node:16.17'
  steps:
     - checkout
     - node/install
     - run:
        name: Install Dependencies
        command: npm i
     - run:
        name: Build
        command: npm run build
     - run: 
        name: Test
        command: npm run test
     - run:
        name: Deploy
        command: npm run deploy
workflows:
 build-workflow:
  jobs:
    - build-test-deploy