version: 2.1
orbs:
 node: circleci/node@5.1.0
jobs:
 build-test-deploy:
  docker:
     - image: 'cimg/node:16.17'
     - image: cimg/postgres:14.0
       environment:
         POSTGRES_USER: postgres
  steps:
     - checkout
     - node/install
     - run: sudo apt-get update
     - run: sudo apt-get install python3-pip
     - run: sudo pip3 install awsebcli
     - run:
        name: Wait for Postgres DBMS to be ready # So we will not execute the automated tests before the DB is ready
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
     - run:
        name: Install Dependencies
        command: npm i
     - run:
        name: Build
        command: npm run build
     - run: 
        name: Test
        command: npm run test
     - run:
        name: Deploy
        command: npm run deploy
workflows:
 build-workflow:
   jobs:
     - build-test-deploy:
         filters:
            branches:
               only:
                - main