version: 2.1
orbs:
node: circleci/node@4.1.0
aws-cli: circleci/aws-cli@1.3.1
jobs:
build:
 docker:
    - image: "cimg/node:14.15"
 steps:
    - node/install
    - checkout
    - run:
        name: Install Dependencies
        command: npm i
    - run:
        name: Build
        command: npm run build 